### ISSUE TITLE
Exporting verified pieces to CSV

### ISSUE THREAD

**Issue by ebuch** [Corridors-of-Time-Transcription/puzzlepieces#13]
- Export all verified pieces into a CSV

**Comment by Lingnik** [comment]
Excors has a better solution because it gives more control of the output format. I drafted a PR for this, but I'll let it sit unmerged in case there are issues with the other method. My PR will need to be adapted to customize the output format. https://github.com/Corridors-of-Time-Transcription/puzzlepieces/pull/31

-----

Proposed solution.

Write a ViewSet connected to the existing Serializer, use rest_framework_csv.renderers.CSVRenderer to handle the magic.

So something like:
```
from rest_framework.viewsets import ModelViewSet
from rest_framework.settings import api_settings
from rest_framework_csv.renderers import CSVRenderer

class ConfidentSolutionViewSet(ModelViewSet):

    queryset = ConfidentSolution.objects.all()
    http_method_names = ['get']
    serializer_class = ConfidentSolutionSerializer
    renderer_classes = tuple(api_settings.DEFAULT_RENDERER_CLASSES) + (CSVRenderer,)

    def get_queryset(self):
        return ConfidentSolution.objects.all()
```

and django-rest-framework-csv installed and an equivalent url doing an .as_view()
