### ISSUE TITLE
Confidence calculations do not have confidence from the team

### ISSUE THREAD

**Issue by Lingnik** [Corridors-of-Time-Transcription/puzzlepieces#41]
Problem statement: Our confidence math is off. We know that it is, we don't know why. The guy who wrote it left the team. Reverse-engineer, document what it's doing and what it's SUPPOSED to be doing, and fix

Relevant code:
https://github.com/Corridors-of-Time-Transcription/puzzlepieces/blob/master/src/collector/views.py#L330

**Comment by Lingnik** [comment]
Logic in collector.views.determineConfidence():

```
Confidence will not be calculated the image is reported as being bad by enough (3) users. (It will be flagged bad.)
Confidence will equal the count of transcriptions if:
    it's less than minimum submissions (5) and not rotated
    it's less than rotated submissions (8) and rotated
Confidence will otherwise equal:
    (transcription_with_most_identical_copies / count_of_all_transcriptions_for_puzzle_piece) * 100

This method also "pins" the likely solution to the puzzle piece if we are confident enough in it:
    If no rotations:
        threshold = ((totalCount * confidenceRatio) / 100) - minSubmissions
    If rotations:
        threshold = ((totalCount * rotatedConfidenceRatio) / 100) - rotatedMinSubmissions
    If biggest > threshold,
        Find the first instance of that transcription object and pin it to the puzzle piece.
```

**Comment by Lingnik** [comment]
The most recent writeup of confidence that I found from mkava:

> Confidence calc is currently stupid simple: total the count of matching submissions based on the hash of the data, check the biggest count against the total count of valid data, and if its over X%, its "confident", where X is currently 70%. So As long as 7 of 10 submission match, we are confident.
> We start checking the calculation at 5 submissions, requiring 4 of 5 to be matching to be mark as confident.

**Comment by Lingnik** [comment]
I wasn't able to identify any transcriptions with dubious confidences. I'm "confident" that they're probably mostly OK. I suspect there's a possibility that confidences could become stale and not update under certain conditions (bad image reports), but I suspect that's intentional.

I submitted #43 to help troubleshoot confidence values ≤7 because I wasn't able to confirm whether the 5-7 case was because of rotation reports or not.

**Comment by mkava** [comment]
I took a real quick look, but the `solution threshold` portion should probably be looked at. I wrote the original version of that method late at a night, and I think enough stuff has changed since I wrote that, both assumptions and features of that service, that another look would be good.
At the very least, should remove the minus operation from the threshold as that was probably a mistake on my part originally.
https://github.com/Corridors-of-Time-Transcription/puzzlepieces/blob/master/src/collector/views.py#L381
I'm guessing I just put a number there without too much thought to make it slightly harder to get to the threshold without realizing how much of an impact it could have past 5 or more transcription submissions or that it would confuse the math.
So
`threshold = ((totalCount * confidenceRatio) / 100) - minSubmissions` to `threshold = ((totalCount * confidenceRatio) / 100)` would get the value to be actually what you expect it to be, instead of less X percent.
Hope that helps.

**Comment by mkava** [comment]
Also...
https://github.com/Corridors-of-Time-Transcription/puzzlepieces/blob/master/src/collector/templates/collector/confidenceDetail.html#L7
https://github.com/Corridors-of-Time-Transcription/puzzlepieces/blob/master/src/collector/views.py#L318

Might be worth looking at that idea and using it to re-run a confidence check on data, so if it looks wrong and code has been updated, you can just recalc individual data points as you want.

**Comment by MisterPeabody** [comment]
Yes, currently the threshold is pushed low by subtracting the minSubmissions. (ie for 9 transcriptions only 2 need to match for a solution to be created)  Although, I would say determining threshold is redundant, rather just check the confidence against the confidenceRatio.
https://github.com/Corridors-of-Time-Transcription/puzzlepieces/blob/ba0e87e5354e2c7ec4dd7b9a230a7a7fd2f34304/src/collector/views.py#L400
`if (not rotationCount and confidence >= confidenceRatio) or (rotationCount and confidence >= rotatedConfidenceRatio)`
`...`
